apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glim.fullname" . }}
  labels:
    {{- include "glim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "glim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "glim.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            - name: GLIM_API_PORT
              value: "{{ .Values.service.apiPort }}"
            - name: GLIM_LDAP_PORT
              value: "{{ .Values.service.ldapPort }}" 
          envFrom:
            - configMapRef:
                name: {{ template "glim.fullname" . }}-env
            - secretRef:
                name: {{ template "glim.secretName" . }}
          volumeMounts:
            - name: data
              mountPath: /home/glim/.glim
          ports:
            - name: rest-port
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
            - name: ldap-port
              containerPort: {{ .Values.service.ldapPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/healthz
              port: {{ .Values.service.apiPort }}
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /v1/readyz
              port: {{ .Values.service.apiPort }}
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "glim.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}

