{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "glim.fullname" . }}
  labels:
    app: {{ template "glim.name" . }}
    chart: {{ template "glim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  GLIM_API_SECRET: {{ .Values.apiSecret | default (randAlphaNum 32) | b64enc | quote }}
  GLIM_INITIAL_ADMIN_PASSWD: {{ .Values.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
  GLIM_INITIAL_SEARCH_PASSWD: {{ .Values.searchPassword | default (randAlphaNum 32) | b64enc | quote }}
{{ end }}
